[package]
name = "auto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
rand = "0.8.4"

regex = "1.5.4"
lazy_static = "1.4.0"
noise = "0.7.0"
bevy_egui = "0.10"